apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudapp-deployment
  labels:
    app: crudapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crudapp
  template:
    metadata:
      labels:
        app: crudapp
    spec:
      containers:
      - name: crudapp
        image: rishabhnama/crudappreact:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: crudapp-service
spec:
  selector:
    app: crudapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000


